### ISSUE TITLE
Add Number Formatting support

### ISSUE THREAD

**Issue by jamesarosen** [jamesarosen/CLDR.js#1]
In the course of doing this, I'd like to use https://github.com/papandreou/node-cldr or https://github.com/Tim-Smart/node-closure as the source for the logic and simply output a small, clean API for consumption.

That is, we will turn this into a project where the only source code is a script (Rake? Grunt?) that pulls in data from node-cldr or node-closure and compiles a couple of JavaScript files, which are then committed to the repository.

**Comment by jamesarosen** [comment]
See https://github.com/jamesarosen/ember-i18n/issues/31 for some background on this.

**Comment by ArmorDarks** [comment]
It seems to be quite old issue...

Are there any plans to implement it? :)

**Comment by jamesarosen** [comment]
Ember-I18n now does pluralization internally and no longer relies on this library, so this library is no longer maintained. I'll add a note to the README.

**Comment by ArmorDarks** [comment]
too bad for those, who doesn't use ember... :(

**Comment by jamesarosen** [comment]
I recommend the [FormatJS](http://formatjs.io/) suite of projects. They likely have one for whatever framework (or non-framework) you're using.

**Comment by ArmorDarks** [comment]
thanks. I'll look into it :)
