### ISSUE TITLE
Ambiguous name CLDR.js vs plurals.js

### ISSUE THREAD

**Issue by vanthome** [jamesarosen/CLDR.js#3]
The title says it all :)
Wouldn't it be sensible to settle on one (file) name?

**Comment by jamesarosen** [comment]
My original idea for this library was to have more CLDR information than just plurals. There would be a `plurals.js`, yes, but also a `formatNumber.js`, a `formatCurrent.js`, and possibly others. I'm not entirely sure I'm going to pursue that now, though.

**Comment by vanthome** [comment]
Ok, then this makes perfect sense!
I think you should keep this name then
