### ISSUE TITLE
More Flexible Pluralization Keys

### ISSUE THREAD

**Issue by vanthome** [jamesarosen/CLDR.js#4]
I think the approach for key naming scheme for "simple plural" and "multiple plural forms" in this lib is more flexible than the one in CLDR.js:

http://i18next.com/pages/doc_features.html#plurals

What do you think about extending it in this direction?

**Comment by jamesarosen** [comment]
This library isn't intended for building your own pluralization rules. It's meant to express all of the CLDR pluralization rules (which should cover nearly every human language used on the Internet) in JavaScript. Are you missing rules for some language?

If not, what features are you looking for?

**Comment by vanthome** [comment]
For example:
The i18ntext framework generates understands keys:

```
translation: {  
  key: '__count__  child',
  key_plural: '__count__  children' 
} 
```

Can this be modeled with 'one' and 'other' in CLDR.js?
Then this can be closed.

**Comment by jamesarosen** [comment]
This library only figures out the right inflection name for a given count. It doesn't do translation lookup. That is, it can tell you

``` javascript
CLDR.pluralForm(9, 'en') // "other"
CLDR.pluralForm(1, 'en') // "one"
```

If you only ever want English rules (1 -> "one", everything else -> "other")' and you want your keys to look like "foo" and "foo_plural", then you hardly need this library. Your translation lookup function would be something like

``` javascript
function translate(keyBase, options) {
  var key = keyBase,
      count = options.count || 1;
  if (count !== 1) { key += "_plural"; }
  return translations[key];
}
```
