### ISSUE TITLE
Publish a new Bower version (1.0.2)

### ISSUE THREAD

**Issue by owain** [jamesarosen/CLDR.js#5]
Is it possible to publish a v1.0.2 of cldr.js to bower please? The current published version (v1.0.1) doesn't include the fix for the `define` requirejs issue that was resolved by #2. 

ember-i18n uses `~1.0` [in it's bower.json dependency](https://github.com/jamesarosen/ember-i18n/blob/master/bower.json#L7) so shouldn't need updating.

**Comment by FoxGit** [comment]
+1

**Comment by jamesarosen** [comment]
I just pushed [v1.0.2](https://github.com/jamesarosen/CLDR.js/tree/v1.0.2). I think that's all Bower needs.
