### ISSUE TITLE
Which CLDR version is your library based on?

### ISSUE THREAD

**Issue by rxaviers** [jamesarosen/CLDR.js#7]
`plurals.js` has a list of locales and plural functions. What relation does all of that have with CLDR? Which CLDR version (the data) is CLDR.js (the library) based on?

On new CLDR data releases, how does `plurals.js` get updated?

Thank you very much

**Comment by jamesarosen** [comment]
> What relation does all of that have with CLDR? Which CLDR version (the data) is CLDR.js (the library) based on?

Whatever was latest on http://cldr.unicode.org/ when I wrote the library.

> On new CLDR data releases, how does plurals.js get updated?

There is no process, but I'm happy to accept pull requests to fix things.

This project will soon be folded into https://github.com/jamesarosen/ember-i18n and closed.

**Comment by rxaviers** [comment]
Thank you
